import { NextRequest, NextResponse } from "next/server";
import { createClient, createServiceRoleClient } from "@/lib/supabase/server";

/**
 * DEVELOPMENT-ONLY sign-in bypass.
 *
 * Why this exists: the only auth method is Google OAuth, which an agent cannot
 * complete — entering someone's Google credentials is not something I will do.
 * That left every signed-in surface unverifiable, which is how a previous
 * session ended up reporting features as working when they could not run at all.
 *
 * THREE INDEPENDENT GUARDS. All must pass:
 *
 *   1. NODE_ENV must not be "production". On Vercel this is always
 *      "production", so this route is dead there — it returns 404, the same as
 *      a route that does not exist, so its presence is not even discoverable.
 *   2. DEV_LOGIN_SECRET must be set in the environment AND match the `key`
 *      query parameter. No secret configured means no bypass, ever.
 *   3. The target email must equal DEV_LOGIN_EMAIL. It cannot be used to
 *      impersonate an arbitrary user by changing a query parameter.
 *
 * It issues a real session through the Supabase admin API rather than forging
 * one, so RLS, credits and admin checks all behave exactly as they do for a
 * genuine login. Nothing downstream is mocked — that is the entire point.
 *
 * If you are reading this while preparing a production deploy: deleting this
 * file is safe and costs nothing but agent convenience.
 */
export async function GET(request: NextRequest) {
  const notFound = () => new NextResponse("Not found", { status: 404 });

  if (process.env.NODE_ENV === "production") return notFound();

  const secret = process.env.DEV_LOGIN_SECRET;
  const email = process.env.DEV_LOGIN_EMAIL;
  if (!secret || !email) return notFound();

  const { searchParams } = new URL(request.url);
  if (searchParams.get("key") !== secret) return notFound();

  /**
   * Behind a tunnel or proxy, `request.url` carries the *internal* host, so
   * redirecting to its origin sends the phone to https://localhost:3000 — which
   * on a phone is the phone itself. The forwarded headers carry the host the
   * browser actually asked for.
   */
  const fwdHost = request.headers.get("x-forwarded-host");
  const host = fwdHost ?? request.headers.get("host") ?? "localhost:3000";
  const proto =
    request.headers.get("x-forwarded-proto") ??
    (host.startsWith("localhost") ? "http" : "https");
  const origin = `${proto}://${host}`;

  const next = searchParams.get("next") ?? "/app";
  const safeNext = next.startsWith("/") && !next.startsWith("//") ? next : "/app";

  const admin = createServiceRoleClient();

  // A magic link generated by the admin API yields a hashed token we can
  // immediately redeem server-side. No email is ever sent.
  const { data, error } = await admin.auth.admin.generateLink({
    type: "magiclink",
    email,
  });

  if (error || !data?.properties?.hashed_token) {
    return NextResponse.json(
      { error: error?.message ?? "Could not generate a dev session" },
      { status: 500 },
    );
  }

  const supabase = await createClient();
  const { error: verifyError } = await supabase.auth.verifyOtp({
    type: "magiclink",
    token_hash: data.properties.hashed_token,
  });

  if (verifyError) {
    return NextResponse.json({ error: verifyError.message }, { status: 500 });
  }

  return NextResponse.redirect(`${origin}${safeNext}`);
}
